services:
  app:
    image: ghcr.io/misenhower/splatoon2.ink
    init: true
    restart: unless-stopped
    environment:
      USE_BROWSERLESS: true
      BROWSERLESS_ENDPOINT: ws://browserless:3000
      SCREENSHOT_HOST: app
    depends_on:
      - browserless
    env_file:
      - .env

  browserless:
    image: ghcr.io/browserless/chromium
    restart: unless-stopped
    environment:
      CONCURRENT: ${BROWSERLESS_CONCURRENT:-1}
