services:
  app:
    build:
      dockerfile: docker/app/Dockerfile
    init: true
    restart: unless-stopped

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./dist:/usr/share/nginx/html:ro
